version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"  # nginx default port is 80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5500:5500"
